routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    $events = \App\Event::all();
//    return view('public.index', compact('events'));
//})->name('home');

Route::get('/', function () {
    return redirect()->route('events.show',1);
});

Route::get('/events/{event}', 'EventsController@show')->name('events.show');
Route::post('/registration', 'RegistrationController@storeRunner')->name('registration.store');
Route::get('/sendMail/{id}', 'RegistrationController@notifyRunner')->name('registration.mail');

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
    Route::get('/', function() {
        $events = \App\Event::all();
        return view('admin.index', compact('events'));
    })->name('dashboard');

    Route::get('events', 'EventsController@index')->name('events.index');
    Route::get('events/{event}/runners', 'EventsController@runnersIndex')->name('events.runners.index');
    Route::get('events/{event}/runners/export', 'EventsController@runnersExport')->name('events.runners.export');
    Route::get('events/{event}/runners/export_all', 'EventsController@runnersExportAll')->name('events.runners.export_all');
    Route::get('events/{event}/runners/export', 'EventsController@runnersExport')->name('events.runners.export');
    Route::get('events/{event}/runners/pending', 'EventsController@runnersPending')->name('events.runners.pending');
    Route::get('events/{event}/runners/create', 'EventsController@runnersCreate')->name('events.runners.create');
    Route::post('events/{event}/runners/create', 'EventsController@runnersStore')->name('events.runners.store');
    Route::get('events/{event}/runners/{runner}', 'EventsController@runnersEdit')->name('events.runners.edit');
    Route::put('events/{event}/runners/{runner}', 'EventsController@runnersUpdate')->name('events.runners.update');
    Route::delete('events/{event}/runners/{runner}', 'EventsController@runnersDestroy')->name('events.runners.destroy');
    Route::get('events/{event}/runners/{runner}/confirm', 'EventsController@runnersConfirm')->name('events.runners.confirm');


//    Route::get('runners/export', 'RunnerController@exportCSV')->name('runners.export');
//    Route::get('runners/print/confirmed', 'RunnerController@printConfirmed')->name('runners.printConfirmed');
//    Route::get('runners/print/unconfirmed', 'RunnerController@printUnconfirmed')->name('runners.printUnconfirmed');
});

app/Runner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Runner extends Model
{
    use SoftDeletes;

    const BIB_NUMBER = null;
    const CONFIRMATION_CODE = null;
    const TERMS_ACCEPTANCE = 1;

    protected $attributes = [
        'bib_number' => self::BIB_NUMBER,
        'confirmation_code' => self::CONFIRMATION_CODE,
        'terms_acceptance' => self::TERMS_ACCEPTANCE,
    ];

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model)
        {
            $model->generateBibNumber(1, 400);
            $model->generateConfirmationCode(15);
        });
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function events()
    {
        return $this->hasManyThrough(Event::class, Race::class);
    }

    public function race()
    {
        return $this->belongsTo(Race::class);
    }

    public function shirt()
    {
        return $this->belongsTo(Shirt::class);
    }

    public function zipcode()
    {
        return $this->belongsTo(Zipcode::class, 'zipcode_id');
    }

    /*
     *
     */
    public function getFullNameAttribute()
    {
        return $this->name . ' ' . $this->last_name;
    }

    public function scopeCount5k($query)
    {
        return $query->where('race_type_id', 1)->count();
    }

    public function scopeCount10k($query)
    {
        return $query->where('race_type_id', 2)->count();
    }

    public function scopeConfirmedCount($query)
    {
        return $query->where('confirmed', 1)->count();
    }

    public function scopeConfirmed($query)
    {
//        return $query->where('confirmed', 1)->where('race_id', '!=', 1)->orderBy('name')->get();
        return $query->where('confirmed', 1)->get();
    }

    public function scopeUnconfirmed($query)
    {
        return $query->where('confirmed', 0)->orderBy('name')->get();
    }

    /*
     * Propietary functions
     */
    protected function generateBibNumber($min, $max)
    {
        do {
            $bib = mt_rand($min, $max);
        } while (!empty(Runner::where('bib_number', $bib)->first()));

        if (is_null($this->attributes['bib_number']))
        {
            $this->attributes['bib_number'] = $bib;
        }
    }

    protected function generateConfirmationCode($length) {
        $randstr = "";
        srand((double) microtime(TRUE) * 1000000);
        //our array add all letters and numbers if you wish
        $chars = array(
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'p',
            'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5',
            '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
            'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');

        for ($rand = 0; $rand <= $length; $rand++) {
            $random = rand(0, count($chars) - 1);
            $randstr .= $chars[$random];
        }

        if (is_null($this->attributes['confirmation_code']))
        {
            $this->attributes['confirmation_code'] = $randstr;
        }
    }
}

app/Http/Controllers/RunnerController.php
<?php

namespace App\Http\Controllers;

use App\City;
use App\Race;
use App\Shirt;
use App\Runner;
use App\RaceType;
use App\Http\Requests\StoreRegistration;
use Illuminate\Http\Request;

class RunnerController extends Controller
{

    public function index()
    {
        $runners = Runner::all();

        return view('admin.runners.index', compact('runners'));
    }

    function create()
    {
        $races = Race::select('id', 'description')->get();
        $cities = City::select('id', 'description')->get();
        $shirts = Shirt::all();

        return view('admin.runners.create', compact('races', 'cities', 'shirts'));
    }



    function edit(Runner $runner)
    {
        $races = Race::select('id', 'description')->get();
        $cities = City::select('id', 'description')->get();
        $shirts = Shirt::select('id', 'size')->get();

        return view('admin.runners.edit', compact('runner', 'races', 'cities', 'shirts'));
    }

    function update(Runner $runner, Request $request)
    {
        $runner->update($request->all());
        return redirect()->route('runners.index');
    }

    function destroy(Runner $runner)
    {
        $runner->delete();
        return redirect()->route('runners.index');
    }

    public function exportCSV()
    {

        $runners = Runner::confirmed();
        $csvExporter = new \Laracsv\Export();

        $csvExporter->beforeEach(function ($runner) {
            $birth_date = new \DateTime($runner->birth_date);
            $now = new \DateTime();
            $interval = $now->diff($birth_date);
            $runner->birth_date = $interval->y;

            if ($runner->race_id == 2) {
                $runner->race_id = "Caminante";
            } elseif ($runner->race_id == 3) {
                $runner->race_id = "5k";
            } elseif ($runner->race_id == 4) {
                $runner->race_id = "Silla de Ruedas";
            }

//            if ($runner->race_type_id == 1 && $runner->gender == 0 && $runner->runner_type == 1) {
//                $runner->race_type_id = "E";
//            } elseif ($runner->race_type_id == 1 && $runner->gender == 1 && $runner->runner_type == 1) {
//                $runner->race_type_id = "F";
//            } elseif ($runner->race_type_id == 1 && $runner->gender == 0 && $runner->runner_type == 2) {
//                $runner->race_type_id = "A";
//            } elseif ($runner->race_type_id == 1 && $runner->gender == 1 && $runner->runner_type == 2) {
//                $runner->race_type_id = "B";
//            } elseif ($runner->race_type_id == 1 && $runner->gender == 0 && $runner->runner_type == 3) {
//                $runner->race_type_id = "C";
//            } elseif ($runner->race_type_id == 1 && $runner->gender == 1 && $runner->runner_type == 3) {
//                $runner->race_type_id = "D";
//            }

            $runner->gender == 0 ? $runner->gender = 'M' : $runner->gender = 'F';
            $runner->sport_type = 'Running';
        });

        $csvExporter->build($runners, [
            'id' => "Bib",
            'name' => 'First Name',
            'last_name' => 'Last Name',
            'gender' => 'Gender',
            'birth_date' => 'Age',
            'race_id' => 'Race',
            'sport_type' => 'Sport type'
        ])->download('5kcandelcoop2019.csv');

    }

    public function confirmed()
    {
        $runners = Runner::confirmed();

        return view('admin.runners.confirmed', compact('runners'));
    }

    public function pending()
    {
        $runners = Runner::unconfirmed();

        return view('admin.runners.pending', compact('runners'));
    }

    public function confirmRunner($id)
    {
        $runner = Runner::findOrFail($id);

        $runner->confirmed = 1;

        $runner->save();

//        Mail::send(new PaymentReceived($runner));

        return redirect()->route('runners.index');
    }

    public function unconfirmRunner($id)
    {
        $runner = Runner::findOrFail($id);

        $runner->confirmed = 0;

        $runner->save();

        return redirect()->route('runners.index');
    }

    public function printConfirmed()
    {
        $report_title = "Corredores Online Confirmados";
        $runners = Runner::confirmed();

        foreach ($runners as $runner) {
            $birth_date = new \DateTime($runner->birth_date);
            $now = new \DateTime();
            $interval = $now->diff($birth_date);
            $runner->birth_date = $interval->y;
        }

        $pdf = \PDF::loadView('admin.reports.confirmed', compact('report_title', 'runners'));
        return $pdf->setPaper('letter', 'landscape')->stream('corredores_confirmados_2017.pdf');
    }

    public function printUnconfirmed()
    {
        $report_title = "Corredores Online Sin Confirmar";
        $runners = Runner::unconfirmed();

        foreach ($runners as $runner) {
            $birth_date = new \DateTime($runner->birth_date);
            $now = new \DateTime();
            $interval = $now->diff($birth_date);
            $runner->birth_date = $interval->y;
        }

        $pdf = \PDF::loadView('admin.reports.confirmed', compact('report_title', 'runners'));
        return $pdf->setPaper('letter', 'landscape')->stream('corredores_confirmados_2017.pdf');
    }

}

resources/views/admin/runners/confirmed.blade.php
@extends('admin.layout.main')

@section('content')

    <div class="card">
        <div class="card-body">
            <div class="card-title">
                <div class="row">
                    <div class="col-sm-12">
                        <h3>Corredores Confirmados ({{ $runners->count() }})</h3>
                    </div>
                    <div class="col-sm-12">
                        <a href="{{ route('runners.printConfirmed') }}" class="btn btn-success">Imprimir Atletas Confirmados</a>
                    </div>
                </div>
            </div>

            <hr>

            <table id="runners" class="table table-responsive-sm table-hover">
                <thead>
                <tr>
                    <th>Bib</th>
                    <th>Nombre</th>
                    <th>T-Shirt</th>
                    <th>Sexo</th>
                    <th>Carrera</th>
                    <th>Código</th>
                    <th>Emergencia</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($runners as $runner)

                    <tr class="{{ $runner->confirmed == 0 ? "table-danger" : "table-success" }}">
                        <td>{{ $runner->bib_number }}</td>
                        <td>{{ $runner->full_name }}</td>
                        <td>{{ $runner->shirt()->first()->size }}</td>
                        <td>{{ $runner->gender == "0" ? 'Masculino' : 'Femenino' }}</td>
                        <td>{{ $runner->race_type()->first()->description }}</td>
                        <td>{{ $runner->confirmation_code }}</td>
                        <td>{{ $runner->emergency_contact }} <br> {{ $runner->emergency_contact_phone }}</td>
                        <td>
                            @if($runner->confirmed == 0)
                                <a href="{{ $runner->id }}/confirm" class="btn btn-sm btn-danger">Confirmar Inscripción</a>
                            @else
                                <a href="{{ $runner->id }}/unconfirm" class="btn btn-sm btn-success">Confirmado</a>
                            @endif
                        </td>
                    </tr>

                @endforeach

                </tbody>
            </table>
        </div>

    </div>

@endsection

@section('scripts')

    <script>
        $(document).ready(function() {
            $('#runners').DataTable({
                responsive: true
            });
        } );
    </script>

@endsection

resources/views/admin/runners/index.blade.php
@extends('admin.layout.main')

@section('content')

    <div class="card">
        <div class="card-body">
            <div class="card-title">
                <div class="row">
                    <div class="col-sm-12">
                        <h3>Lista de Corredores ({{ \App\Runner::count() }})</h3>
                    </div>
                    <div class="col-sm-12">
                        <a href="{{ route('runners.create') }}" class="btn btn-primary">Inscribir Corredor</a>
                        <a href="{{ route('runners.export') }}" class="btn btn-success">Descargar CSV</a>
                    </div>
                </div>
            </div>

            <hr>

            <table id="runners" class="table table-responsive-lg table-hover">
                <thead>
                <tr>
                    <th>Bib</th>
                    <th>Nombre</th>
                    <th>T-Shirt</th>
                    <th>Sexo</th>
                    <th>Carrera</th>
                    <th>Método de Pago</th>
                    <th>Emergencia</th>
                </tr>
                </thead>
                <tbody>
                @foreach($runners as $runner)

                    <tr class="{{ $runner->confirmed == 0 ? "table-danger" : "table-success" }}">
                        <td>{{ $runner->id }}</td>
                        <td><a href="{{ route('runners.edit', $runner) }}">{{ $runner->full_name }}</a></td>
                        <td>{{ $runner->shirt()->first()->size }}</td>
                        <td>{{ $runner->gender == "0" ? 'Masculino' : 'Femenino' }}</td>
                        <td>{{ $runner->race->description }}</td>
                        <td>{{ $runner->payment_method }}</td>
                        <td>{{ $runner->emergency_contact }} <br> {{ $runner->emergency_contact_phone }}</td>
                    </tr>

                @endforeach

                </tbody>
            </table>
        </div>

    </div>

@endsection

@section('scripts')

    <script>
        $(document).ready(function() {
            $('#runners').DataTable({
                responsive: true,
            });
        } );
    </script>

@endsection

resources/views/admin/runners/pending.blade.php
@extends('admin.layout.main')

@section('content')

    <div class="card">
        <div class="card-body">
            <div class="card-title">
                <div class="row">
                    <div class="col-sm-12">
                        <h2>{{ $event->name }}- Corredores por Confirmar ({{ $runners->count() }})</h2>
                    </div>

                    <div class="col-sm-12">
{{--                        <a href="{{ route('runners.printUnconfirmed') }}" class="btn btn-danger">Imprimir Atletas Sin Confirmar</a>--}}
                    </div>
                </div>
            </div>

            <hr>

            <table id="runners" class="table table-responsive-lg table-hover">
                <thead>
                <tr>
                    <th>Bib</th>
                    <th>Nombre</th>
                    <th>T-Shirt</th>
                    <th>Sexo</th>
                    <th>Carrera</th>
                    <th>Código</th>
                    <th>Emergencia</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($runners as $runner)

                    <tr class="{{ $runner->confirmed == 0 ? "table-danger" : "table-success" }}">
                        <td>{{ $runner->id }}</td>
                        <td>{{ $runner->full_name }}</td>
                        <td>{{ $runner->shirt()->first()->size }}</td>
                        <td>{{ $runner->gender == "0" ? 'Masculino' : 'Femenino' }}</td>
                        <td>{{ $runner->race->description }}</td>
                        <td>{{ $runner->confirmation_code }}</td>
                        <td>{{ $runner->emergency_contact }} <br> {{ $runner->emergency_contact_phone }}</td>
                        <td>
                            @if($runner->confirmed == 0)
                                <a href="{{ route('events.runners.confirm', ['event' => $event, 'runner' => $runner]) }}" class="btn btn-sm btn-danger">Confirmar Inscripción</a>
                            @else
                                <a href="{{ $runner->id }}/unconfirm" class="btn btn-sm btn-success">Confirmado</a>
                            @endif
                        </td>
                    </tr>

                @endforeach

                </tbody>
            </table>
        </div>

    </div>

@endsection

@section('scripts')

    <script>
        $(document).ready(function() {
            $('#runners').DataTable({
                responsive: true,
            });
        } );
    </script>

@endsection